### ISSUE TITLE
Crash when viewing server's apps

### ISSUE THREAD

**Issue by michiels** [intercity/intercity-next#188]
I'm trying to visit the apps overview of a service and getting a crash. Here's the output from `production.log`:

```
I, [2016-08-30T13:38:48.034967 #22]  INFO -- : [dce31cba-4279-4373-b630-8262e2c90ff5] Redirected to http://37.139.13.229/servers/2/apps
I, [2016-08-30T13:38:48.035972 #22]  INFO -- : [dce31cba-4279-4373-b630-8262e2c90ff5] Completed 302 Found in 26ms (ActiveRecord: 3.5ms)
I, [2016-08-30T13:38:48.227013 #22]  INFO -- : [eaad48a7-a9ad-4b26-9227-e5f61babfb55] Started GET "/servers/2/apps" for 80.113.22.243 at 2016-08-30 13:38:48 +0000
I, [2016-08-30T13:38:48.229193 #22]  INFO -- : [eaad48a7-a9ad-4b26-9227-e5f61babfb55] Processing by AppsController#index as HTML
I, [2016-08-30T13:38:48.229554 #22]  INFO -- : [eaad48a7-a9ad-4b26-9227-e5f61babfb55]   Parameters: {"server_id"=>"2"}
D, [2016-08-30T13:38:48.231984 #22] DEBUG -- : [eaad48a7-a9ad-4b26-9227-e5f61babfb55]   User Load (0.4ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
D, [2016-08-30T13:38:48.234432 #22] DEBUG -- : [eaad48a7-a9ad-4b26-9227-e5f61babfb55]    (0.6ms)  SELECT COUNT(*) FROM "users"
D, [2016-08-30T13:38:48.236497 #22] DEBUG -- : [eaad48a7-a9ad-4b26-9227-e5f61babfb55]   Setting Load (0.7ms)  SELECT  "settings".* FROM "settings" ORDER BY "settings"."id" ASC LIMIT $1  [["LIMIT", 1]]
D, [2016-08-30T13:38:48.238713 #22] DEBUG -- : [eaad48a7-a9ad-4b26-9227-e5f61babfb55]   Server Load (0.3ms)  SELECT  "servers".* FROM "servers" WHERE "servers"."id" = $1 LIMIT $2  [["id", 2], ["LIMIT", 1]]
D, [2016-08-30T13:38:48.241725 #22] DEBUG -- : [eaad48a7-a9ad-4b26-9227-e5f61babfb55]   CACHE (0.1ms)  SELECT  "servers".* FROM "servers" WHERE "servers"."id" = $1 LIMIT $2  [["id", 2], ["LIMIT", 1]]
D, [2016-08-30T13:38:48.246006 #22] DEBUG -- : [eaad48a7-a9ad-4b26-9227-e5f61babfb55]   App Load (0.9ms)  SELECT "apps".* FROM "apps" WHERE "apps"."server_id" = 2
I, [2016-08-30T13:38:48.252737 #22]  INFO -- : [eaad48a7-a9ad-4b26-9227-e5f61babfb55]   Rendering apps/index.html.erb within layouts/application
I, [2016-08-30T13:38:48.262147 #22]  INFO -- : [eaad48a7-a9ad-4b26-9227-e5f61babfb55]   Rendered servers/_heading.html.erb (7.9ms)
I, [2016-08-30T13:38:48.262744 #22]  INFO -- : [eaad48a7-a9ad-4b26-9227-e5f61babfb55]   Rendered apps/index.html.erb within layouts/application (9.5ms)
I, [2016-08-30T13:38:48.263514 #22]  INFO -- : [eaad48a7-a9ad-4b26-9227-e5f61babfb55] Completed 500 Internal Server Error in 33ms (ActiveRecord: 2.9ms)
F, [2016-08-30T13:38:48.265823 #22] FATAL -- : [eaad48a7-a9ad-4b26-9227-e5f61babfb55]   
F, [2016-08-30T13:38:48.266500 #22] FATAL -- : [eaad48a7-a9ad-4b26-9227-e5f61babfb55] ActionView::Template::Error (undefined method `[]' for nil:NilClass):
F, [2016-08-30T13:38:48.267107 #22] FATAL -- : [eaad48a7-a9ad-4b26-9227-e5f61babfb55]     10:   <ul class="nav nav-tabs">
F, [2016-08-30T13:38:48.267431 #22] FATAL -- : [eaad48a7-a9ad-4b26-9227-e5f61babfb55]     11:   </ul>
F, [2016-08-30T13:38:48.267705 #22] FATAL -- : [eaad48a7-a9ad-4b26-9227-e5f61babfb55]     12: </div>
F, [2016-08-30T13:38:48.267967 #22] FATAL -- : [eaad48a7-a9ad-4b26-9227-e5f61babfb55]     13: <%= render("servers/outdated", server: server) unless server.up_to_date? %>
F, [2016-08-30T13:38:48.268231 #22] FATAL -- : [eaad48a7-a9ad-4b26-9227-e5f61babfb55]     14: <%= render "flashes" -%>
F, [2016-08-30T13:38:48.268445 #22] FATAL -- : [eaad48a7-a9ad-4b26-9227-e5f61babfb55]   
F, [2016-08-30T13:38:48.268650 #22] FATAL -- : [eaad48a7-a9ad-4b26-9227-e5f61babfb55] lib/version_parser.rb:8:in `parse'
F, [2016-08-30T13:38:48.268857 #22] FATAL -- : [eaad48a7-a9ad-4b26-9227-e5f61babfb55] app/models/server.rb:30:in `up_to_date?'
F, [2016-08-30T13:38:48.269062 #22] FATAL -- : [eaad48a7-a9ad-4b26-9227-e5f61babfb55] app/views/servers/_heading.html.erb:13:in `_app_views_servers__heading_html_erb___3904836057367850508_47225577377020'
F, [2016-08-30T13:38:48.269271 #22] FATAL -- : [eaad48a7-a9ad-4b26-9227-e5f61babfb55] app/views/apps/index.html.erb:1:in `_app_views_apps_index_html_erb___4183454217650962978_47225577561360'
```

**Comment by jvanbaarsen** [comment]
@michiels Is this on production?

**Comment by michiels** [comment]
@jvanbaarsen It's my own Intercity instance install on a DigitalOcean droplet.

**Comment by jvanbaarsen** [comment]
:+1:

**Comment by michiels** [comment]
@jvanbaarsen I think another user hit this error too. Just as a :+1:

**Comment by jvanbaarsen** [comment]
@michiels Was this a server where IC and Dokku runs on the same server?

**Comment by michiels** [comment]
@jvanbaarsen Correct

**Comment by w0www** [comment]
Same error

**Comment by jvanbaarsen** [comment]
@w0www Thanks for reporting back! I'll take a look later this week.

**Comment by w0www** [comment]
Thanks to you for this work! Is very interesting ;).
